flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.1.0.0
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- asn1-encoding-0.9.4
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.1
- attoparsec-0.13.1.0
- base-compat-0.9.1
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.2
- byteable-0.1.1
- case-insensitive-1.2.0.8
- cereal-0.5.4.0
- clock-0.7.2
- connection-0.2.7
- cookie-0.4.2.1
- cryptonite-0.22
- data-default-class-0.1.2.0
- dlist-0.8.0.2
- exceptions-0.8.3
- hashable-1.2.5.0
- hourglass-0.2.10
- http-client-0.5.6.1
- http-client-tls-0.3.4
- http-types-0.9.1
- integer-logarithms-1.0.1
- memory-0.14.1
- mime-types-0.1.0.7
- mtl-2.2.1
- network-2.6.3.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- optparse-applicative-0.13.1.0
- parsec-3.1.11
- pem-0.2.2
- primitive-0.6.2.0
- random-1.1
- regex-base-0.93.2
- regex-tdfa-1.2.2
- scientific-0.3.4.10
- socks-0.5.5
- stm-2.4.4.1
- streaming-commons-0.1.17
- tagged-0.8.5
- tasty-0.11.0.4
- tasty-hunit-0.9.2
- text-1.2.2.1
- time-locale-compat-0.1.1.3
- tls-1.3.9
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- unordered-containers-0.2.7.2
- uri-encode-1.5.0.5
- utf8-string-1.0.1.1
- uuid-types-1.0.3
- vector-0.12.0.0
- x509-1.6.5
- x509-store-1.6.2
- x509-system-1.6.4
- x509-validation-1.6.5
- zlib-0.6.1.2
resolver: ghc-8.0.1
